# Generated by Django 4.0.1 on 2025-05-16 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sico', '0002_video_patient_progress_videoprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='is_required',
            field=models.BooleanField(default=True),
        ),
    ]
