# Generated by Django 4.0.1 on 2025-05-17 10:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sico', '0004_question_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='Option Text')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Is Correct Answer?')),
                ('score', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(-10), django.core.validators.MaxValueValidator(10)], verbose_name='Score')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
            ],
            options={
                'verbose_name': 'Answer Option',
                'verbose_name_plural': 'Answer Options',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PatientResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answered_at', models.DateTimeField(auto_now_add=True, verbose_name='Answer Time')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='sico.patient', verbose_name='Patient')),
            ],
            options={
                'verbose_name': 'Patient Response',
                'verbose_name_plural': 'Patient Responses',
                'ordering': ['-answered_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-created_at'], 'verbose_name': 'Question', 'verbose_name_plural': 'Questions'},
        ),
        migrations.RemoveField(
            model_name='question',
            name='correct_answer',
        ),
        migrations.AddField(
            model_name='question',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Creation Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='explanation',
            field=models.TextField(blank=True, help_text='Detailed explanation of the correct answer', verbose_name='Answer Explanation'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('MC', 'Multiple Choice'), ('SC', 'Single Choice'), ('TF', 'True/False')], db_index=True, default='MC', max_length=2, verbose_name='Question Type'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(help_text='Enter the full question text here', verbose_name='Question Text'),
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.AddField(
            model_name='patientresponse',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_responses', to='sico.question', verbose_name='Question'),
        ),
        migrations.AddField(
            model_name='patientresponse',
            name='selected_option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sico.answeroption', verbose_name='Selected Option'),
        ),
        migrations.AddField(
            model_name='answeroption',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='sico.question', verbose_name='Question'),
        ),
        migrations.AlterUniqueTogether(
            name='patientresponse',
            unique_together={('patient', 'question')},
        ),
    ]
