# Generated by Django 4.0.1 on 2025-05-17 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sico', '0005_answeroption_patientresponse_alter_question_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoprogress',
            name='completion_percentage',
            field=models.FloatField(default=0.0),
        ),
    ]
